### ISSUE TITLE
[Feature Request] JSON Schema for sitemap

### ISSUE THREAD

**Issue by solarhell** [NewFuture/miniprogram-template#14]
https://developers.weixin.qq.com/miniprogram/dev/reference/configuration/sitemap.html

I want to know if you have already set out to do this? Or i can help.

**Comment by NewFuture** [comment]
yes, all JSON schemas of MiniProgram are hosted here https://github.com/NewFuture/miniprogram-json-schema

**Comment by NewFuture** [comment]
NewFuture/miniprogram-json-schema#1
