### ISSUE TITLE
npm 国内镜像找不到 miniprogram-build 5.2.1

### ISSUE THREAD

**Issue by xxyuze** [NewFuture/miniprogram-template#16]
这个库很棒，是目前唯一强大又可用的命令行工具。
但是经过测试，如果npm切换到了淘宝镜像源，install会失败，因为找不到miniprogram-build 5.2.1，最新版本是5.2.0。
如果切换到国外的源没有问题，我想这会导致很多人第一次使用无法启动项目。

**Comment by mutoe** [comment]
国内用 yarn 很快

**Comment by xxyuze** [comment]
是的，我的yarn也切换了国内源，尝试安装，会提示选择版本，最新是5.2.0。
我已经安装成功，我是怕其他人第一次使用无法启动会选择放弃。
我想可以在教程里说明一下这个情况。

**Comment by mutoe** [comment]
可以, 不过yarn并不需要切换源吧, 我就用的自带的源很快呀

**Comment by xxyuze** [comment]
有段时间很慢才切换的，一般情况应该很快

**Comment by NewFuture** [comment]
cnpm 上的源似乎没有同步最新版本
https://cnpmjs.org/package/miniprogram-build 上面显示的还是5.2.0

手动同步了一下 
https://cnpmjs.org/sync/miniprogram-build#logid=3406513

这个镜像服务不应该自动同步的吗 😂
