### ISSUE TITLE
tslib 打包上传后无法正确在真机上运行

### ISSUE THREAD

**Issue by mutoe** [NewFuture/miniprogram-template#20]
在微信开发者工具中可运行, 打包上传后 安卓下小程序一直卡在启动画面 在ios下打开调试模式 控制台显示 `tslib.js is not defined. `

不知道是什么原因, 我尝试过build后手动将 tslib 放在 `dist/node_modules` 目录下使用开发者工具 先构建 npm 然后ES6转ES5, 也不行, 开发者工具使用调试模式就可以正常运行

可以确定不是偶发, 我近几天使用该模版重构的项目均出现此问题, 不知道这个 `tslib` 库是做什么的, 我试过不加载该依赖仍然无法启动, 请求总部支援 😂

### 环境
开发者工具 `1.02.1905151`
微信 `7.0.4`
基础库 `2.6.6`

**Comment by mutoe** [comment]
真机调试偶尔会报这些错误
![图片](https://user-images.githubusercontent.com/9391981/59029206-3fe2b100-8890-11e9-9685-11c17c71c254.png)

**Comment by mutoe** [comment]
ios 下调试报错
<img width="1080" alt="图片" src="https://user-images.githubusercontent.com/9391981/59029575-3148c980-8891-11e9-9b22-d56fe34c1e24.png">

**Comment by mutoe** [comment]
已解决

### 解决办法
1. 从 `package.json` 的 `dependencies` 中移除 `tslib` 依赖
2. `tsconfig.json` 中关闭 `noEmitHelpers` `importHelpers` `esModuleInterop` 三个选项

误打误撞的解决了, 不知道这是不是个bug, 等仓库的主人来处理 @NewFuture

**Comment by NewFuture** [comment]
tslib是使一些es7高级语法如装饰器，async/await 等这些东西注入的runtime

可以贴一下编译后的代码看看

**Comment by mutoe** [comment]
https://github.com/mutoe/handnote-miniprogram/tree/include-dist
这里是含有dist目录的项目

**Comment by NewFuture** [comment]
没有发现tslib相关的问题?
有时候，编译太快，重启一下开发工具就行了

**Comment by mutoe** [comment]
刚才试了一下, 不得行. 有可能不是tslib的问题 我逐一排查下, 有问题再重新打开

**Comment by NewFuture** [comment]
那个项目 page not found 也出现了

**Comment by NewFuture** [comment]
https://github.com/mutoe/handnote-miniprogram/blob/431b38bde61d3285e6f139f6b50dc53d906690b9/src/pages/setting/menstrual/menstrual.ts#L11

@mutoe 这个应该是Page里面export 的问题
`export interface MenstrualOptions`

**Comment by mutoe** [comment]
@NewFuture 果然是这个原因.. 一直在纳闷这个怎么了 原来不能导出interface的吗.. 感谢 👍
