### ISSUE TITLE
关于globalData的问题

### ISSUE THREAD

**Issue by mutoe** [NewFuture/miniprogram-template#27]
我注意到,在一次提交(e74d52750c2905f51b6f2b83498b485eba1e0184)中, `app.ts`中的MyApp接口被移除了, 并且导入了另外单独的globalData文件.

但是我认为这样做会导致MyApp中自己定义的方法会失去类型检查, 下面是一个例子

在`app.ts`中
<img width="529" alt="图片" src="https://user-images.githubusercontent.com/9391981/60749604-da88f980-9fce-11e9-9db3-4fca5ba19c48.png">

在`pages/index/index.ts`中
<img width="335" alt="图片" src="https://user-images.githubusercontent.com/9391981/60749611-f12f5080-9fce-11e9-906c-22f821bdaddc.png">

这个更改导致app中的方法不好用了, 是否可以继续保留MyApp接口, 像下面一样

``` ts
import { GlobalData } from "/model/global-data";

export interface MyApp {
    customFunc: () => typeof GlobalData
}

App<MyApp>({
    customFunc() {
        console.log(GlobalData);
        return GlobalData
    },
});
```

如果可以, 我稍后将发起一个PR

**Comment by NewFuture** [comment]
这样使用都是没问题的，但是这里不推荐绑定到App上(就像所有数据和API都注册到jQuery上一样)。

这里推荐的做法是 
* 将数据和方法都 `模块化`,即在需要的地方`import`对应的数据或者函数,由数据模块管理和暴露操作接口;
* 而不是 ~~全部绑定到App上~~ (虽然你可以这么做，小程序的默认demo也是这么写的，但是这并不适合项目的维护和管理)

**Comment by mutoe** [comment]
你说的对, 是我陷入了定式思维, 分离出来也避免了啰嗦的接口定义. 感谢您的回答🙏
