### ISSUE TITLE
代码编译缺少wxss文件的问题

### ISSUE THREAD

**Issue by wang997722** [NewFuture/miniprogram-template#36]
项目重新编译时,经常会出现wxss文件缺失的问题,大部分情况出现在组件内,必须手动重新保存下丢失的sass文件才可以,每次重新打包都得检查一下有没有缺失文件.
![WX20190902-160503](https://user-images.githubusercontent.com/43238764/64099389-bca3ff00-cd9b-11e9-9210-d806be0b0e1b.png)

**Comment by NewFuture** [comment]
这个是在微信开发工具里看到的?

**Comment by wang997722** [comment]
> 这个是在微信开发工具里看到的？

项目的dist文件夹

**Comment by NewFuture** [comment]
是基于目前最新版的(上周日更新)的模板项目么？

之前微信开发工具会有锁文件导致无法更新的问题,现在重新start的时候会自动关闭开发工具

**Comment by wang997722** [comment]
> 是基于目前最新版的（上周日更新）的模板项目么？
> 
> 之前微信开发工具会有锁文件导致无法更新的问题，现在重新启动的时候会自动关闭开发工具

不是 0.1.1版本 请问 怎么更新呢?  是把新项目模板下载下来然后迁移进去?

**Comment by wang997722** [comment]
刚才更新了下   依然有这个问题, 页面上组件超过两个就有概率出现这个问题,dist目录下缺少css文件

**Comment by NewFuture** [comment]
组件和页面对于这个build工具来说没有区别(实际项目二十左右个组件也没有出现过丢失情况)

我用最新的开发工具RC版调试，确实发现样式没加载进来(但是文件已经编译好了，重新保存一下又正常了，nightly 版本的正常)
开发工具的BUG https://developers.weixin.qq.com/community/develop/doc/000c6ec0988e70868e093eb6756000?_at=1567507668031


你可以build完之后列出所有components的 wxss确认一下
```bash
ls dist/components/**/*.wxss
```

1. 确实有wxss没编译可以share一下project我调查一下
2. 如果wxss文件存在应该是开发工具的bug，可以换个版本
