### ISSUE TITLE
wxml  属性变量自动换行问题

### ISSUE THREAD

**Issue by w0330t** [NewFuture/miniprogram-template#40]
我原本写的代码是这样
![image](https://user-images.githubusercontent.com/4970238/65381765-13ad4c00-dd2a-11e9-8906-1309e273e054.png)
但是保存了之后代码格式化之后变成了这样
![image](https://user-images.githubusercontent.com/4970238/65381782-6d157b00-dd2a-11e9-9750-c2169d99f8b1.png)
微信的编译器就开始报错
![image](https://user-images.githubusercontent.com/4970238/65381785-81f20e80-dd2a-11e9-9434-f26271c23264.png)
我把代码改成了这样，问题依旧
![image](https://user-images.githubusercontent.com/4970238/65381844-f8dbd700-dd2b-11e9-9b06-6a35f1a73c71.png)

还有一个事，我这边情况有点特殊，开发和微信的ide分别是两个电脑，我:目前在开发机远程访问的微信ide，有点慢，请问dist目录能否可以自定义设置目录，比如输出为D:\dist这种绝对路径

**Comment by w0330t** [comment]
我尝试更改`.prettierrc`文件中的`printWidth`，好像没起作用
![image](https://user-images.githubusercontent.com/4970238/65381896-1b222480-dd2d-11e9-9029-128241ff8cdd.png)

**Comment by NewFuture** [comment]
这是微信开发工具模板解析的bug，
暂时可以通过 
```html
<!-- prettier-ignore-attribute style -->
```
class 名过长可以用
```html
<!-- prettier-ignore-attribute class -->
```

来阻止自动格式化


输入的时候应该有自动提示

**Comment by w0330t** [comment]
关于dist目录输出的事，请问可以实现吗？或者我另外开一个issus？

**Comment by NewFuture** [comment]
> 关于dist目录输出的事，请问可以实现吗？或者我另外开一个issus？

这个是指什么？可以开一个issue说明一下
