### ISSUE TITLE
关于自定义dist目录的问题

### ISSUE THREAD

**Issue by w0330t** [NewFuture/miniprogram-template#42]
目前情况有点特殊。
开发和微信的调试分别是两个电脑，我目前在开发机远程访问调试机，整个代码目录也放在调试机里。
我想的是开发机本地存放开发目录，输出目录则直接远程编译到调试机。
所以问一下dist目录能否可以自定义设置目录，比如在windows下输出为D:\dist这种绝对路径

**Comment by NewFuture** [comment]
在配置文件指定`dist`参数即可
```json
{ 
"dist":"d:/dist"
}
```
或者命令行参数中指定`dist`参数即可
`mp build --dist="d:/dist"`

详细配置 可参考 https://github.com/NewFuture/miniprogram-build#%E5%8F%82%E6%95%B0-options
