### ISSUE TITLE
upload上传代码能否设置备注信息

### ISSUE THREAD

**Issue by AnoLu** [NewFuture/miniprogram-template#49]
现在上传时使用的备注信息为saving，能否自定义？还有上传的版本号呢

**Comment by NewFuture** [comment]
可以的

版本号默认 使用package.json里的版本号
message 默认 使用最后一条commit message

也可以自定义 参数，可以看这部分
https://github.com/NewFuture/wechat-devtool#%E9%AB%98%E7%BA%A7%E7%94%A8%E6%B3%95
