### ISSUE TITLE
是否可以在 SCSS 中 import 微信样式 WXSS 文件并获得正确的转换路径。

### ISSUE THREAD

**Issue by redblue9771** [NewFuture/miniprogram-template#62]
app.scss

```scss
@import "@vant/weapp/common/index.wxss";
```
预期的输出

app.wxss
```css
@import "/miniprogram_npm/@vant/weapp/common/index.wxss";
```

错误的输出

app.wxss
```css
@import url(@vant/weapp/common/index.wxss);
```

**Comment by NewFuture** [comment]
直接这样写，让打包工具不处理

```scss
@import "/miniprogram_npm/@vant/weapp/common/index.wxss";
```

还有一种方式是导入纯scss/css的包如weui (安装到devDependencies，有赞这个不确定)
```
@import "~weui"; 
```

**Comment by redblue9771** [comment]
> 直接这样写，让打包工具不处理
> 
> ```css-scss
> @import "/miniprogram_npm/@vant/weapp/common/index.wxss";
> ```
> 
> 还有一种方式是导入纯scss/css的包如weui (安装到devDependencies，有赞这个不确定)
> 
> ```
> @import "~weui"; 
> ```

直接写会被转译为
 ```css
@import url(/miniprogram_npm/@vant/weapp/common/index.wxss);
```
会有url包裹，而不是一个纯字符串~

**Comment by NewFuture** [comment]
这里@符合被过滤了 更新 v6.9.0 试试 https://www.npmjs.com/package/miniprogram-build

**Comment by redblue9771** [comment]
> 这里@符合被过滤了 更新 v6.9.0 试试 https://www.npmjs.com/package/miniprogram-build

❤可以了，谢谢！
