### ISSUE TITLE
Replace "miniprogram-api-typings" with "@types/wechat-miniprogram".

### ISSUE THREAD

**Issue by redblue9771** [NewFuture/miniprogram-template#63]
Using ["@types/wechat-miniprogram"](https://github.com/wechat-miniprogram/api-typings) as a dependency is more in line with TypeScript specifications.

**Comment by NewFuture** [comment]
这个他们终于放提交到`DefinitelyTyped`上去了🤣. 

欢饮提个PR更新一下 😸

**Comment by redblue9771** [comment]
原来可以说中文的🤣，他们最近开始干点事儿了
> 这个他们终于放提交到`DefinitelyTyped`上去了🤣. 
> 
> 
> 
> 欢饮提个PR更新一下 😸
